<a href="https://colab.research.google.com/github/kkr016/pandas_implementation/blob/main/pandas_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
data_1 = pd.read_csv('/content/status_details.csv', encoding='latin-1')

In [3]:
data_1.head()

,ï»¿Timestamp,orderId,distributorId,originalDistributorId,hubId,quantity,Amount,hubCode,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,13/09/22 2:30,49,1,1.0,1.0,4,555.04,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13/09/22 2:30,203,1,1.0,1.0,4,851.04,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13/09/22 2:30,143,1,1.0,1.0,1,1137.64,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13/09/22 2:30,118,1,1.0,1.0,3,859.92,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13/09/22 2:30,167,1,1.0,1.0,6,11453.20,a,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data_1.shape

(11801, 15)

In [5]:
data_1.isnull().sum()

ï»¿Timestamp                 0
orderId                      0
distributorId                0
originalDistributorId       18
hubId                       18
quantity                     0
Amount                       0
hubCode                      0
Unnamed: 8               11801
Unnamed: 9               11801
Unnamed: 10              11801
Unnamed: 11              11801
Unnamed: 12              11801
Unnamed: 13              11801
Unnamed: 14              11801
dtype: int64

In [6]:
data_1.quantity.isna().sum()

0

In [7]:
data_1=data_1.drop(['Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14'], axis=1)

In [8]:
data_1.isnull().sum()

ï»¿Timestamp              0
orderId                   0
distributorId             0
originalDistributorId    18
hubId                    18
quantity                  0
Amount                    0
hubCode                   0
dtype: int64

In [9]:
data_1.rename(columns = {'ï»¿Timestamp':'Timestamp'}, inplace = True)

In [10]:
data_1.head()

,Timestamp,orderId,distributorId,originalDistributorId,hubId,quantity,Amount,hubCode
0,13/09/22 2:30,49,1,1.0,1.0,4,555.04,a
1,13/09/22 2:30,203,1,1.0,1.0,4,851.04,a
2,13/09/22 2:30,143,1,1.0,1.0,1,1137.64,a
3,13/09/22 2:30,118,1,1.0,1.0,3,859.92,a
4,13/09/22 2:30,167,1,1.0,1.0,6,11453.20,a

In [11]:
data_1.dtypes

Timestamp                 object
orderId                    int64
distributorId              int64
originalDistributorId    float64
hubId                    float64
quantity                   int64
Amount                   float64
hubCode                   object
dtype: object

In [12]:
data_1["Timestamp"] = pd.to_datetime(data_1["Timestamp"])

In [13]:
data_1.originalDistributorId.unique()

array([ 1., nan,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 33., 34., 35., 36., 15., 16., 17., 18., 19., 37., 38., 39.,
       20., 21., 40., 22., 14., 23., 24., 25., 26., 27., 41., 42., 28.,
       29., 30., 31., 32., 43., 44.])

In [14]:
data_1.hubId.unique()

array([ 1., nan,  2.,  4.])

In [15]:
data_1.describe()

,orderId,distributorId,originalDistributorId,hubId,quantity,Amount
count,11801.000000,11801.000000,11783.000000,11783.000000,11801.000000,1.180100e+04
mean,135.066350,5.075248,5.141560,1.179156,11.397000,2.473934e+03
std,77.616713,5.024256,5.280053,0.414759,312.916591,2.442132e+04
min,1.000000,1.000000,1.000000,1.000000,1.000000,4.930000e+00
25%,68.000000,1.000000,1.000000,1.000000,1.000000,3.628000e+02
50%,136.000000,4.000000,4.000000,1.000000,3.000000,8.487000e+02
75%,202.000000,6.000000,6.000000,1.000000,6.000000,1.965040e+03
max,270.000000,32.000000,44.000000,4.000000,32330.000000,1.898584e+06

In [16]:
data_2 = pd.read_csv('/content/status.csv', encoding='latin-1')

In [17]:
data_2.shape

(270, 2)

In [18]:
data_2.isnull().sum()

orderId    0
status     0
dtype: int64

In [19]:
data_2.dtypes

orderId     int64
status     object
dtype: object

In [20]:
data_2.describe()

          orderId
count  270.000000
mean   135.500000
std     78.086491
min      1.000000
25%     68.250000
50%    135.500000
75%    202.750000
max    270.000000

In [21]:
data_3 = pd.merge(data_1, data_2)

In [22]:
data_3.head()

,Timestamp,orderId,distributorId,originalDistributorId,hubId,quantity,Amount,hubCode,status
0,2022-09-13 02:30:00,49,1,1.0,1.0,4,555.04,a,status_b
1,2022-09-13 02:30:00,49,1,1.0,1.0,1,210.90,a,status_b
2,2022-09-13 02:30:00,49,1,1.0,1.0,2,709.16,a,status_b
3,2022-09-13 02:30:00,49,1,1.0,1.0,3,410.88,a,status_b
4,2022-09-13 02:30:00,49,1,1.0,1.0,2,944.40,a,status_b

In [23]:
data_3.shape

(11801, 9)

In [24]:
data_1.shape

(11801, 8)

In [25]:
data_3.dtypes

Timestamp                datetime64[ns]
orderId                           int64
distributorId                     int64
originalDistributorId           float64
hubId                           float64
quantity                          int64
Amount                          float64
hubCode                          object
status                           object
dtype: object

In [26]:
data_3.groupby(['orderId']).count()

,Timestamp,distributorId,originalDistributorId,hubId,quantity,Amount,hubCode,status
orderId,,,,,,,,
1,44,44,43,44,44,44,44,44
2,41,41,41,41,41,41,41,41
3,41,41,41,41,41,41,41,41
4,53,53,53,53,53,53,53,53
5,35,35,35,35,35,35,35,35
...,...,...,...,...,...,...,...,...
266,50,50,50,49,50,50,50,50
267,43,43,43,43,43,43,43,43
268,34,34,34,34,34,34,34,34
269,37,37,37,37,37,37,37,37
270,32,32,32,32,32,32,32,32

In [27]:
data_3

,Timestamp,orderId,distributorId,originalDistributorId,hubId,quantity,Amount,hubCode,status
0,2022-09-13 02:30:00,49,1,1.0,1.0,4,555.04,a,status_b
1,2022-09-13 02:30:00,49,1,1.0,1.0,1,210.90,a,status_b
2,2022-09-13 02:30:00,49,1,1.0,1.0,2,709.16,a,status_b
3,2022-09-13 02:30:00,49,1,1.0,1.0,3,410.88,a,status_b
4,2022-09-13 02:30:00,49,1,1.0,1.0,2,944.40,a,status_b
...,...,...,...,...,...,...,...,...,...
11796,2022-09-13 12:05:00,38,2,2.0,1.0,10,567.06,a,status_b
11797,2022-09-13 12:11:00,38,13,13.0,2.0,1,238.05,b,status_b
11798,2022-09-13 12:33:00,38,5,5.0,1.0,2,1857.51,a,status_b
11799,2022-09-13 12:37:00,38,5,5.0,1.0,2,229.84,a,status_b
11800,2022-09-13 12:42:00,38,5,5.0,1.0,1,591.60,a,status_b

#Question no. 1

1.	Find the number of orders on hourly basis.
Output Format
 
![image.png]()

In [28]:
data_3["Timestamp"].min(), data_3["Timestamp"].max()

(Timestamp('2022-09-13 02:30:00'), Timestamp('2022-09-13 14:42:00'))

In [29]:
data_3["Timestamp"].max() - data_3["Timestamp"].min()

Timedelta('0 days 12:12:00')

In [30]:
q1=data_3.groupby([data_3["Timestamp"].dt.hour])["orderId"].count()
header=['orderCount']
csv_q1 = q1.to_csv('1.csv', header=header, index_label='hour')

In [62]:
q1

Timestamp
2     2280
3      873
4      644
5      557
6      853
7     1298
8     1491
9     1192
10      98
11     543
12    1941
13      30
14       1
Name: orderId, dtype: int64

#Question no. 2

2.	Substitute the missing values in the column 'originalDistributorId' with the values in the column 'distributorId'.
Output Format

![image.png]()

In [32]:
data_3.isnull().sum()

Timestamp                 0
orderId                   0
distributorId             0
originalDistributorId    18
hubId                    18
quantity                  0
Amount                    0
hubCode                   0
status                    0
dtype: int64

In [33]:
data_3[['distributorId','originalDistributorId']].describe()

       distributorId  originalDistributorId
count   11801.000000           11783.000000
mean        5.075248               5.141560
std         5.024256               5.280053
min         1.000000               1.000000
25%         1.000000               1.000000
50%         4.000000               4.000000
75%         6.000000               6.000000
max        32.000000              44.000000

In [34]:
data_3.distributorId.unique()

array([ 1,  2,  3,  4,  5,  6, 12, 17, 19, 10, 13, 26, 20,  7, 21, 24, 28,
       11, 18, 15,  8, 27, 14,  9, 16, 25, 23, 29, 32, 31, 22, 30])

In [35]:
data_3.originalDistributorId.unique()

array([ 1.,  2.,  3.,  4.,  5.,  6., 12., 17., 19., 10., 13., 26., 20.,
        7., 21., 24., 28., 11., 18., 15.,  8., 27., nan, 36., 41.,  9.,
       16., 25., 23., 33., 29., 32., 14., 39., 38., 40., 34., 37., 31.,
       22., 43., 44., 42., 30., 35.])

In [36]:
rows_with_nan=list(np.where(data_3["originalDistributorId"].isna())[0])
print("count : ",len(rows_with_nan), "Index :", rows_with_nan,)

count :  18 Index : [384, 1117, 2459, 3497, 3641, 4665, 4922, 5088, 6612, 6774, 7111, 8294, 8347, 8373, 8749, 10146, 10769, 11297]

In [37]:
data_3[['distributorId','originalDistributorId']].loc[rows_with_nan]

       distributorId  originalDistributorId
384                1                    NaN
1117               1                    NaN
2459               2                    NaN
3497               2                    NaN
3641               4                    NaN
4665               4                    NaN
4922               7                    NaN
5088               5                    NaN
6612               5                    NaN
6774               6                    NaN
7111               8                    NaN
8294               1                    NaN
8347               4                    NaN
8373               1                    NaN
8749               5                    NaN
10146              3                    NaN
10769              6                    NaN
11297              3                    NaN

In [38]:
data_3['originalDistributorId'].fillna(data_3['distributorId'], inplace=True)

In [39]:
data_3[['distributorId','originalDistributorId']].loc[rows_with_nan]

       distributorId  originalDistributorId
384                1                    1.0
1117               1                    1.0
2459               2                    2.0
3497               2                    2.0
3641               4                    4.0
4665               4                    4.0
4922               7                    7.0
5088               5                    5.0
6612               5                    5.0
6774               6                    6.0
7111               8                    8.0
8294               1                    1.0
8347               4                    4.0
8373               1                    1.0
8749               5                    5.0
10146              3                    3.0
10769              6                    6.0
11297              3                    3.0

In [40]:
q2=data_3[['distributorId','originalDistributorId']]
csv_q2 = q2.to_csv('2.csv')

In [63]:
q2

       distributorId  originalDistributorId
0                  1                    1.0
1                  1                    1.0
2                  1                    1.0
3                  1                    1.0
4                  1                    1.0
...              ...                    ...
11796              2                    2.0
11797             13                   13.0
11798              5                    5.0
11799              5                    5.0
11800              5                    5.0

[11801 rows x 2 columns]

#Question no. 3

3.	Find the number of entries where originalDistributorId is not same as distributorId.
Output Format
![image.png]()

In [41]:
count=0

for i,j in zip(data_3.distributorId,data_3.originalDistributorId):
  if i != j:
    count+=1

q3 = pd.DataFrame([[count]],columns=['Count'],index=None)

csv_q3 = q3.to_csv('3.csv')

In [64]:
q3

   Count
0     35

#Question no. 4a

a.	Find the hubCode having the highest number of order with ' status_b'
Output Format

![image.png]()

In [42]:
data_3.groupby('hubCode')['orderId'].count()

hubCode
a    9788
b    1964
f      49
Name: orderId, dtype: int64

In [43]:
w=data_3.groupby(['status']).get_group('status_b')
w.status.unique()

array(['status_b'], dtype=object)

In [44]:
w1 = w.groupby('hubCode')['orderId'].count().reset_index()
q4a = w1['hubCode'].loc[list(np.where(w1['orderId'].max()))[0]]


csv_q4a = q4a.to_csv('4a.csv')

In [65]:
q4a

0    a
Name: hubCode, dtype: object

#Question no. 4b

b.	Find the hubCode having highest percentage of status_b
Output Format
![image.png]()

In [45]:
w2 = w.groupby('hubCode')['status'].count().reset_index()
s=w2.status.sum()
w2['percentage'] = w2['status']/s
w2

  hubCode  status  percentage
0       a    6603    0.829627
1       b    1326    0.166604
2       f      30    0.003769

In [46]:
q4b = w1['hubCode'].loc[list(np.where(w2['percentage'].max()))[0]]

csv_q4b = q4b.to_csv('4b.csv')

In [66]:
q4b

0    a
Name: hubCode, dtype: object

#Question no. 5

5.	Create a table giving the visibility of ‘distributorId’ wise, the count of orders in different status and the percentage of status_b (status) of total orders as shown below
Output Format
![image.png]()

In [47]:
data_3.head(1)

,Timestamp,orderId,distributorId,originalDistributorId,hubId,quantity,Amount,hubCode,status
0,2022-09-13 02:30:00,49,1,1.0,1.0,4,555.04,a,status_b

In [48]:
z1 = data_3.groupby('distributorId')['status'].apply(lambda x: (x=='status_a').sum()).reset_index()

In [49]:
z2 = data_3.groupby('distributorId')['status'].apply(lambda x: (x=='status_b').sum()).reset_index()

In [50]:
z = data_3.groupby(['distributorId'])['orderId'].count().reset_index()

In [51]:
z['Status_a (count)'] = z1['status']
z['Status_b (count)'] = z2['status']
z['Status_b (percentage)'] = z['Status_b (count)']*100/z['orderId']
z.rename(columns = {'orderId':'totalOrders'}, inplace = True)
z

,distributorId,totalOrders,Status_a (count),Status_b (count),Status_b (percentage)
0,1,4274,1365,2909,68.062705
1,2,695,227,468,67.338129
2,3,785,253,532,67.770701
3,4,568,197,371,65.316901
4,5,1604,548,1056,65.835411
5,6,1252,404,848,67.731629
6,7,161,54,107,66.459627
7,8,108,37,71,65.740741
8,9,98,34,64,65.306122
9,10,541,173,368,68.022181
10,11,130,49,81,62.307692
11,12,452,145,307,67.920354
12,13,411,123,288,70.072993
13,14,36,14,22,61.111111
14,15,133,43,90,67.669173
15,16,78,28,50,64.102564
16,17,81,22,59,72.839506
17,18,118,28,90,76.271186
18,19,6,1,5,83.333333
19,20,87,26,61,70.114943
20,21,6,2,4,66.666667
21,22,1,0,1,100.000000
22,23,35,15,20,57.142857
23,24,99,34,65,65.656566
24,25,3,2,1,33.333333
25,26,5,4,1,20.000000
26,27,20,12,8,40.000000
27,28,7,1,6,85.714286
28,29,1,0,1,100.000000
29,30,1,0,1,100.000000
30,31,1,1,0,0.000000
31,32,4,0,4,100.000000

In [52]:
q5= z
csv_q5 = q5.to_csv('5.csv')

In [67]:
q5

,distributorId,totalOrders,Status_a (count),Status_b (count),Status_b (percentage)
0,1,4274,1365,2909,68.062705
1,2,695,227,468,67.338129
2,3,785,253,532,67.770701
3,4,568,197,371,65.316901
4,5,1604,548,1056,65.835411
5,6,1252,404,848,67.731629
6,7,161,54,107,66.459627
7,8,108,37,71,65.740741
8,9,98,34,64,65.306122
9,10,541,173,368,68.022181
10,11,130,49,81,62.307692
11,12,452,145,307,67.920354
12,13,411,123,288,70.072993
13,14,36,14,22,61.111111
14,15,133,43,90,67.669173
15,16,78,28,50,64.102564
16,17,81,22,59,72.839506
17,18,118,28,90,76.271186
18,19,6,1,5,83.333333
19,20,87,26,61,70.114943
20,21,6,2,4,66.666667
21,22,1,0,1,100.000000
22,23,35,15,20,57.142857
23,24,99,34,65,65.656566
24,25,3,2,1,33.333333
25,26,5,4,1,20.000000
26,27,20,12,8,40.000000
27,28,7,1,6,85.714286
28,29,1,0,1,100.000000
29,30,1,0,1,100.000000
30,31,1,1,0,0.000000
31,32,4,0,4,100.000000

#Question no. 6

6.	Substitute the null values of the column 'hubId' with the mode of that column
Output Format
![image.png]()

In [53]:
data_3.hubId.isnull().sum()

18

In [54]:
rows_with_nan_hubid=list(np.where(data_3["hubId"].isna())[0])
print("count :",len(rows_with_nan_hubid), "Index :", rows_with_nan_hubid)

count : 18 Index : [664, 1715, 2228, 2518, 2628, 3245, 3378, 3791, 4621, 5549, 5640, 5698, 5733, 6714, 8471, 9291, 9391, 11670]

In [55]:
data_3['hubId'].mode()

0    1.0
dtype: float64

In [56]:
data_3.fillna(data_3['hubId'].mode()[0], inplace = True)

In [57]:
q6=data_3['hubId']

csv_q6 = q6.to_csv('6.csv')

In [58]:
data_3.hubId.isnull().sum()

0

In [68]:
q6

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
11796    1.0
11797    2.0
11798    1.0
11799    1.0
11800    1.0
Name: hubId, Length: 11801, dtype: float64

#Question no. 7

7.	Print all the distinct combination of ‘hubCode’ and ‘distributorId’
Output Format
![image.png]()

In [59]:
data_3[['hubCode', 'distributorId']]

      hubCode  distributorId
0           a              1
1           a              1
2           a              1
3           a              1
4           a              1
...       ...            ...
11796       a              2
11797       b             13
11798       a              5
11799       a              5
11800       a              5

[11801 rows x 2 columns]

In [60]:
w3=data_3.groupby(['hubCode', 'distributorId']).size().reset_index()
q7=w3.drop(0, axis=1)

In [61]:
csv_q7 = q7.to_csv('7.csv')

In [69]:
q7

   hubCode  distributorId
0        a              1
1        a              2
2        a              3
3        a              4
4        a              5
5        a              6
6        a              7
7        a             15
8        a             16
9        a             17
10       a             18
11       a             19
12       a             21
13       a             22
14       a             27
15       a             29
16       a             31
17       a             32
18       b              8
19       b              9
20       b             10
21       b             11
22       b             12
23       b             13
24       b             20
25       b             23
26       b             24
27       b             25
28       f             14
29       f             26
30       f             28
31       f             30